name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    name: build and push
    #if: github.event.pull_request.merged == true
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: disable fork sync
        run: 'curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GH_TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" -X PUT https://api.github.com/repos/Eisaichen/linkwarden/actions/workflows/auto-sync.yml/disable'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: eisai/linkwarden:latest,eisai/linkwarden:${{ github.sha }}

      - name: enable fork sync
        run: 'curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GH_TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" -X PUT https://api.github.com/repos/Eisaichen/linkwarden/actions/workflows/auto-sync.yml/enable'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
